### ISSUE TITLE
gr_relay_rules doesn't seem to do anything

### ISSUE THREAD

**Issue by gdhbashton** [echocat/puppet-graphite#152]
Hullo,

I'm using current git `b49b55f` of the module on CentOS 7 and when I specify `gr_relay_rules` and do a Puppet run, nothing changes on disk:

```    
gr_relay_rules              => {
                                    'default' => {
                                                  'default'    => true,
                                                  destinations => [ 'graphiteb.node.consul:2004:a', 'graphitec.node.consul:2004:a' ],
                                                  continue     => true,
                                    }
},
```

I'd expect the `relay-rules.conf.erb` to fire and write a new `relay-rules.conf` in `/opt/graphite/conf` but nothing happens. All the other params I'm setting (e.g. `gr_relay_destinations`, `gr_carbonlink_hosts`) are being applied as expected.

Any ideas would be warmly welcomed :)

Cheers,
Gavin.

**Comment by dwerder** [comment]
This is pretty easy. You have to enable carbon relay funktion.
This is done via setting `gr_enable_carbon_relay` to `true`

**Comment by gdhbashton** [comment]
It's always obvious after the event. Thanks :)
