### ISSUE TITLE
Module attempts to install django-tagging on every run

### ISSUE THREAD

**Issue by huasome** [echocat/puppet-graphite#155]
Looks like module version 5.10.0 attempts to install django-tagging on every run (and thus triggering a database schema import and refresh of carbon-cache).

```
Info: Class[Graphite::Install]: Scheduling refresh of Class[Graphite::Config]
Info: Class[Graphite::Install]: Scheduling refresh of Exec[Initial django db creation]
Info: Class[Graphite::Config]: Scheduling refresh of Exec[Initial django db creation]
Info: Class[Graphite::Config]: Scheduling refresh of Exec[Chown graphite for web user]
Info: Class[Graphite::Config]: Scheduling refresh of Service[carbon-cache]
Notice: /Stage[main]/Graphite::Config/Exec[Initial django db creation]: Triggered 'refresh' from 2 events
Info: /Stage[main]/Graphite::Config/Exec[Initial django db creation]: Scheduling refresh of Exec[Chown graphite for web user]
Notice: /Stage[main]/Graphite::Config/Service[carbon-cache]: Triggered 'refresh' from 1 events
Notice: /Stage[main]/Graphite::Config/Exec[Chown graphite for web user]: Triggered 'refresh' from 2 events
```

This happens every run.

**Comment by dwerder** [comment]
Can you provide more information, please. 
Which OS, puppet version, and your module configuration.

**Comment by huasome** [comment]
Ubuntu 14.04, puppet version 3.7.4. The module is all configured through hiera and I don't have any either gr_django_tagging_pkg or gr_django_tagging_ver configured. gr_pip_install is left as default.

**Comment by erikrh** [comment]
I can confirm this as well. Ubuntu 14.04, Puppet 3.4.3, default module configuration.

**Comment by jarshwah** [comment]
Good timing (with the bug report) - I upgraded to 5.10 yesterday and I'm getting the same problem. I thought I'd done something wrong.

RedHat 6 - puppet 3.7.4

**Comment by mvisonneau** [comment]
Same for me on Ubuntu 14.04 since 5.10 :(

**Comment by dwerder** [comment]
Ok, so we just skip Ubuntu support :-D 
No, seriosly, i will take a look at it. So I just have Centos 6.6 machines running my graphites.

**Comment by dwerder** [comment]
But if someone already has a solution or PR. Just let me know.

**Comment by mvisonneau** [comment]
Hope this will help ! :)

**Comment by dwerder** [comment]
@jarshwah  can you confirm that the fixed master works on your CentOS 6 ?
@erikrh @huasome can you confirm the fix on your Ubuntu systems?

Please use the updated master. If all works fine, I will upload a new release to the puppetforge

**Comment by huasome** [comment]
Yep, that fixed the problem. I didn't test out the master branch but setting the hiera variables
```
graphite::gr_django_tagging_pkg: 'django-tagging'
graphite::gr_django_tagging_ver: '0.3.4'
```
fixed it.
