### ISSUE TITLE
Graphite + Grafana

### ISSUE THREAD

**Issue by TinajaLabs** [echocat/puppet-graphite#163]
I'm really new to puppet so this might be associated with #78 and #130.

I have success with the basic graphite setup like this:
```
  class { 'graphite':
    gr_apache_port => '8081',
    gr_max_updates_per_second => 200,
    gr_timezone               => 'America/Los_Angeles',
    secret_key                => 'blahblahjkdsladska',
   	gr_storage_schemas => [
	    {
	      name       => 'carbon',
	      pattern    => '^carbon\.',
	      retentions => '1m:90d'
	    },
	    {
	      name       => 'tinaja',
	      pattern    => '^tinaja\.',
	      retentions => '1m:90d,5m:30d,60m:365d'
	    },
	    {
	      name       => 'default',
	      pattern    => '.*',
	      retentions => '60:1d'
	    }
  ]
  }
```
But when I want to include grafana on the same host, and declare the apache class I get an error indicating that apche is referenced twice.
```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Duplicate declaration: Package[apache2] is already declared in file /etc/puppet/environments/development/modules/apache/manifests/init.pp:103; cannot redeclare at /etc/puppet/environments/development/modules/graphite/manifests/config_apache.pp:20 on node freecinga
```

My goal is to make sure apache, graphite, and grafana are all running on the same host.  I use carbon/whisper for data collection and graphite web for quick tests. Grafana is used to build separate dashboards.  Ideally, these would be aliased so I could access the web host like this:
* http://myhost (it's working page)
* http://myhost/graphite
* http://myhost/grafana

Thanks for any advice,
Chris.

**Comment by dwerder** [comment]
See README:

https://github.com/echocat/puppet-graphite#configure-graphite-with-grafana

**Comment by TinajaLabs** [comment]
Yes.  Thanks.  I tried that approach.

First problem is that it fails to create the /opt/graphite directory:
```
root@freecinga:~# puppet agent --test    
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for freecinga.jumano.salt
Info: Applying configuration version '1426572124'
Error: Cannot create /opt/graphite/webapp; parent directory /opt/graphite does not exist
```
Then the errors cascade from there.

As I mentioned before, the simple approach I posted above, seemed to work OK but I would like to add the grafana charts also.

If I manually create the /opt/graphite dir, it creates the webapp dir, but that is all.  After setting up some apache configs:

Notice: /Stage[main]/Main/Node[freecinga.jumano.salt]/Apache::Vhost[graphite.my.domain]/Concat[25-graphite.my.domain.conf]/Exec[concat_25-graphite.my.domain.conf]/returns: executed successfully
Notice: /Stage[main]/Main/Node[freecinga.jumano.salt]/Apache::Vhost[graphite.my.domain]/Concat[25-graphite.my.domain.conf]/Exec[concat_25-graphite.my.domain.conf]: Triggered 'refresh' from 11 events
Notice: /Stage[main]/Main/Node[freecinga.jumano.salt]/Apache::Vhost[graphite.my.domain]/Concat[25-graphite.my.domain.conf]/File[25-graphite.my.domain.conf]/ensure: defined content as '{md5}e798042c410704b4d32b0d658a33ad90'
Info: Concat[25-graphite.my.domain.conf]: Scheduling refresh of Class[Apache::Service]
Notice: /Stage[main]/Main/Node[freecinga.jumano.salt]/Apache::Vhost[graphite.my.domain]/File[25-graphite.my.domain.conf symlink]/ensure: created
Info: /Stage[main]/Main/Node[freecinga.jumano.salt]/Apache::Vhost[graphite.my.domain]/File[25-graphite.my.domain.conf symlink]: Scheduling refresh of Class[Apache::Service]
Error: Could not set 'file' on ensure: No such file or directory - /opt/graphite/conf/storage-schemas.conf20150317-19969-qn4enk.lock at 189:/etc/puppet/environments/development/modules/graphite/manifests/config.pp
Error: Could not set 'file' on ensure: No such file or directory - /opt/graphite/conf/storage-schemas.conf20150317-19969-qn4enk.lock at 189:/etc/puppet/environments/development/modules/graphite/manifests/config.pp
Wrapped exception:
No such file or directory - /opt/graphite/conf/storage-schemas.conf20150317-19969-qn4enk.lock

BTW, the client is ubuntu 12.04 and the server is running Centos 6.5. I've got puppet 3.7.4 running on both.

Thanks for your help...

**Comment by dwerder** [comment]
Ok. I see the problem.

Try that config:

```
class { 'graphite': ... }-> 
apache::vhost { graphite.my.domain:
  port    => '80',
  docroot => '/opt/graphite/webap
....
}
```

The rest should be the same as in the example. Graphite has to be installed before the apache config, because it creates the /opt/graphite/ folders.

**Comment by dwerder** [comment]
And the same for grafana. First install grafana and then the vhost.

grafana -> vhost(grafana)

**Comment by TinajaLabs** [comment]
Cool.  That makes sense.  I'll give that a try a little later and let you know.

Thanks,
Chris.

**Comment by TinajaLabs** [comment]
oops...  seems closer.

```
Error: Could not apply complete catalog: Found 1 dependency cycle:
(Anchor[graphite::end] => Class[Graphite] => Apache::Vhost[graphite.my.domain] => File[/opt/graphite/webapp] => File[/opt/graphite/webapp/graphite/local_settings.py] => Class[Graphite::Config] => Anchor[graphite::end])
Try the '--graph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz
```

My new config:
```
include '::apache'


class { 'graphite':
  gr_web_server => 'none'
}->
apache::vhost { 'graphite.my.domain':
  port    => '80',
  docroot => '/opt/graphite/webapp',
  wsgi_application_group      => '%{GLOBAL}',
  wsgi_daemon_process         => 'graphite',
  wsgi_daemon_process_options => {
    processes          => '5',
    threads            => '5',
    display-name       => '%{GROUP}',
    inactivity-timeout => '120',
  },
  wsgi_import_script          => '/opt/graphite/conf/graphite.wsgi',
  wsgi_import_script_options  => {
    process-group     => 'graphite',
    application-group => '%{GLOBAL}'
  },
  wsgi_process_group          => 'graphite',
  wsgi_script_aliases         => {
    '/' => '/opt/graphite/conf/graphite.wsgi'
  },
  headers => [
    'set Access-Control-Allow-Origin "*"',
    'set Access-Control-Allow-Methods "GET, OPTIONS, POST"',
    'set Access-Control-Allow-Headers "origin, authorization, accept"',
  ],
  directories => [{
    path => '/media/',
    order => 'deny,allow',
    allow => 'from all'}
  ]
}


class {'grafana':
  graphite_host      => 'graphite.my.domain',
  elasticsearch_host => 'elasticsearach.my.domain',
  elasticsearch_port => 9200,
}->
apache::vhost { 'grafana.my.domain':
  servername      => 'grafana.my.domain',
  port            => 80,
  docroot         => '/opt/grafana',
  error_log_file  => 'grafana_error.log',
  access_log_file => 'grafana_access.log',
  directories     => [
    {
      path            => '/opt/grafana',
      options         => [ 'None' ],
      allow           => 'from All',
      allow_override  => [ 'None' ],
      order           => 'Allow,Deny',
    }
  ]
}

```

Thanks,
Chris.

**Comment by scottsuch** [comment]
This is the same issue I had months ago and just resigned to wait until 6.0 was released to spend more time.

**Comment by dwerder** [comment]
Ok. One last try for today :D 

Try:
```
class { 'graphite': .... }

apache::vhost { 'graphite.my.domain':
  ...
  require => Class['graphite::install'];
}
```

**Comment by scottsuch** [comment]
Still not working so well with the example changes.
Using my example repo [here](https://github.com/scottsuch/puppetized-grafana-example)
I swapped default.pp with this one. [default.pp](https://gist.github.com/scottsuch/4c229937fc3777411614)
Output - https://gist.github.com/scottsuch/4c229937fc3777411614

**Comment by TinajaLabs** [comment]
Sorry for the tedium but I appreciate any help.

I have cleared all interaction on my puppet setup and still no joy.

What I have discovered is that somewhere when graphite is installing, it failes to create the directories in /opt.  If I manually create:
```
graphite
graphite/bin
graphite/conf
graphite/webapp
etc.
```
it goes pretty well but eventually fails because carbon-cache.py is not installed:
```
Error: Could not start Service[carbon-cache]: Execution of '/etc/init.d/carbon-cache start' returned 2: python: can't open file '/opt/graphite/bin/carbon-cache.py': [Errno 2] No such file or directory
```
Interestingly, I see one file in ```/opt/graphite/bin/```; it is carbon-logrotate.sh

In my facter file I see osfamily is ```debian```.

Would you please indicate where the install happens and where I should be looking for this issue.  I'm not saying it is a problem with your code but maybe it is my version of ubuntu 12.04, or python, or ruby, or of the distro it is pulling?  As I mentioned, I'm really new to puppet and ruby and this whole ecosystem, but this problem is a good learning.

Thanks for advice,
Chris.

**Comment by dwerder** [comment]
The installation is done in the file 'manifests/install.pp'. The configuration comes fro the 'manifests/config_*' files. And used parameter defaults are taken from 'manifests/params.pp'

I have not much time at the moment. So I have no time for debugging this right now.

**Comment by TinajaLabs** [comment]
Thanks for the details. I appreciate your help and understand being busy.  I'll look at those sections.

Some more test and the results I put in a gist at:
https://gist.github.com/TinajaLabs/dc15218db80aa85d2a8c

This was tested on a beaglebone black with basic image of debian 7.8...

Perhaps something might be obvious to you when you get some time.

Thanks,
Chris.

**Comment by TinajaLabs** [comment]
After all this hassle it seems there was a problem with graphite 0.9.12.  I switched like this and it went much more smoothly.
```
      gr_carbon_ver => '0.9.13',
      gr_whisper_ver => '0.9.13',
      gr_graphite_ver => '0.9.13',
```
Now on to the little details like installing minimal java to run elasticsearch to save grafana dashboards.

Thanks for your help.
