### ISSUE TITLE
graphite only shows top bar

### ISSUE THREAD

**Issue by brettswift** [echocat/puppet-graphite#167]
I used to have this working, but now when I build a new server graphite only shows the top login bar, and the entire body of the page is white. 

https://github.com/brettswift/puppet-sensu_suite/blob/38692f2a65ea54b249f78aa8d4797e5aea34521b/manifests/mygraphite.pp

That is my graphite configuraiton.   When I click the "dashboard" link on graphite, it gives me a "drop to merge" message, and nothing else.

Any idea what causes this? Or is there something funky I did with that configuration?

**Comment by lreed** [comment]
I am also having this same issue.  I used the configs as per https://github.com/echocat/puppet-graphite#configure-graphite-with-grafana for the VHOST setups.   

I tried to debug looking at Django options etc but was not able to figure it out.

Thanks
