### ISSUE TITLE
graphite with default setup shows no graphs

### ISSUE THREAD

**Issue by brettswift** [echocat/puppet-graphite#168]
I have a vagrant box using this module with default configuration, with only one modification - enabling cors. 

I have a feature branch that wraps sensu, and graphite, which can demonstrate this problem: 

https://github.com/brettswift/puppet-sensu_suite/tree/feature/separate_graphite_grafana

My configuration: 
```puppet
  class { 'graphite':
    gr_web_cors_allow_from_all => true,
  }
```

And what I see: 
![image](https://cloud.githubusercontent.com/assets/723989/7024256/aa246736-dcf8-11e4-8912-12b829327911.png)

**Comment by dwerder** [comment]
I have now clue. Is this still a problem?
