### ISSUE TITLE
Install to FHS paths + other improvements

### ISSUE THREAD

**Issue by melan** [echocat/puppet-graphite#171]
I worked on the module to make it able to install graphite into non /opt/graphite location (that was a requirement). So many paths were moved into parameters.

Does it make any sense to create a pull request for the changes or nobody needs that?

Thanks

**Comment by dwerder** [comment]
Send the PR.

**Comment by JoepWeijers** [comment]
This enhancement would solve some of my problems as well, so please send the Pull Request!

**Comment by lord2800** [comment]
@melan This would also solve some of my problems.

**Comment by JoshiiSinfield** [comment]
I've pretty much done the work for this, I just haven't tested it yet. I'll test and fix it asap and do a PR when I'm done.

Cheers,
Josh

https://github.com/CDLSoftware/puppet-graphite/tree/addSupportForFHSPathsAsParams

**Comment by dwerder** [comment]
Open the PR against develop branch then, please. Thanks in advance.

**Comment by JoshiiSinfield** [comment]
@dwerder Will do. Cheers.
