### ISSUE TITLE
"gr_pip_install" => "false" stil trying to set up GCC

### ISSUE THREAD

**Issue by dene14** [echocat/puppet-graphite#179]
Module trying to set up GCC even if "gr_pip_install" has been set to "false". I guess there is no reason for that and it's just a bug...

**Comment by dwerder** [comment]
Bug is such a hard word. Lets say it can be optimized.

**Comment by decibelhertz** [comment]
With recent work I did for https://github.com/echocat/puppet-graphite/issues/166, this issue is pretty easy to factor in.  See https://github.com/echocat/puppet-graphite/pull/204

**Comment by dwerder** [comment]
Thanks and good work.
