### ISSUE TITLE
Problems with pip install on CentOS 7

### ISSUE THREAD

**Issue by dene14** [echocat/puppet-graphite#180]
According to puppet bugtracker: https://projects.puppetlabs.com/issues/15980
pip install doesn't works throwing a error: 
Error: /Stage[main]/Graphite::Install/Package[django-tagging]/ensure: change from absent to 0.3.4 failed: Could not update: Could not locate the pip command.

NoPip install doesn't works here too... module contains hardcoded paths to /opt/graphite w/o any ability to override, whereas package now properly aligned to standard FS hierarcy (doesn't push whole stack to /opt)

**Comment by dwerder** [comment]
Man, incompatible? I am running this module on CentOS 6 and RHEL 6 boxes.

**Comment by dwerder** [comment]
Renamed title to be more useful.

**Comment by dwerder** [comment]
What version of puppet, facter and most importent, how does your module config looks like.

**Comment by dene14** [comment]
puppetmaster 3.7.4,
puppet agent 3.6.1 (from epel)

Config... It is really not important, coz I've checked graphite package's install paths (EPEL7), they currently incompatible. 
Pip provider doesn't work due to puppet's bug :(
 I've tried many, finished with pip_install tries:
  "graphite::gr_pip_install"            : true,
  "graphite::gr_django_tagging_pkg"     : "python-django-tagging",
  "graphite::gr_django_tagging_ver"     : "0.3.4"

If you'd like, you can contact me to discuss in IRC: dene14@FreeNode

**Comment by dwerder** [comment]
My first hint is to not use the package. I am not the maintainer of the EPEL graphite package. If they do not use the default install paths, then it gets really tricky.

I have no CentOS 7 at hand, but I know that there are a lot of installation out there which work out of the box with that module.

At the moment I have no time to refactor the whole module to use other paths, then the default one.
But you can provide a PR if you want ;)

**Comment by dwerder** [comment]
And why do you use another djange package then the one, which is selected in the params.pp for RHEL7? And did you try to install 0.9.12 or something like 0.10.0?

**Comment by dene14** [comment]
I've tried a lot of combinations... The main problem is in config.pp
you've done a lot of work to make the manifest compatible with package install but all these efforts are defeated by path's hardcode in config.pp (/opt/graphite)

I bet there is no ability to install from package on many systems defined as compatible, coz normal packager will never package software delivered to /opt.

Install from PIP will work in most cases (on centos7 it won't due to puppet bug described above), however this is dirty way to manage software in production systems in a couple of reasons:
- having GCC on prod server - has potential security implication
- you can't normally control reproducibility of environment (that's what packaging was invented for)
- pypi could be considered as an untrusted source by many reasons

**Comment by dwerder** [comment]
Ok, your are using EPEL and talking about gcc and pypi to be a security issue?

I know that there are PIP installations out there. Even with CentOS 7. And there are solutions for that problem linked in the bug ticket mentioned above.

The problem with the hardcoded path is already discussed https://github.com/echocat/puppet-graphite/issues/171 . But I have no resources at hand to provide that at this moment. So if no one provides a pull request, I can not tell you when I will have time to take a look at this myself.

**Comment by dene14** [comment]
Daniel, I have absolutely no offence on you :) and I understand how open source works, so no estimation is okay with me. I've simply reported an issue.

If I will decide to proceed with that module I provide a PR

**Comment by dwerder** [comment]
No problem. We do not use the RPMs, coz they simply do not exist years ago ;-D

**Comment by slloyd1994** [comment]
Hi, just wanted say thanks for this great module. However when upgrading CentOS from 6.5 to 7, I am also getting this error:
Could not update: Could not locate the pip command.

**Comment by dfxprima** [comment]
There is a bug filed upstream to fix the pip provider. It affects 6.7 and 7.x.  [PUP-3829](https://tickets.puppetlabs.com/browse/PUP-3829)

**Comment by dwerder** [comment]
Fixed by puppet in https://tickets.puppetlabs.com/browse/PUP-4997
