### ISSUE TITLE
Please support new bulk and prefetch options in .9.13, as well as remote render.

### ISSUE THREAD

**Issue by greenaar** [echocat/puppet-graphite#190]
Could you add flags to turn on the new bulk response and prefetch options 0.9.13 supports?  Also, if you could expose the remote render options, that would help immensely.

**Comment by dwerder** [comment]
You could sen dme a pull request with the flags/options you want. I do not use 0.9.13 at the moment. So I have no clue, what flags are new ;-)

**Comment by greenaar** [comment]
I've sent you a pull request with that in mind, thanks!

**Comment by dwerder** [comment]
requires #191
