### ISSUE TITLE
Change from `if !defined(Package[...]) { ... }` to `ensure_packages` is problematic

### ISSUE THREAD

**Issue by cataphract** [echocat/puppet-graphite#209]
Commit fa83afdb00a22214ec4b36757d34d4cc77ab0a34 changed of the installation of the `python-pip` package from:

```
if ! defined(Package[$::graphite::params::python_pip_pkg]) {
  package { $::graphite::params::python_pip_pkg :
    provider => undef, # default to package provider auto-discovery
    before   => [
      Package['django-tagging'],
      Package['twisted'],
      Package['txamqp'],
    ]
 }
}
```

to

```
ensure_packages($::graphite::params::graphitepkgs)
```

This change is unfortunate, because `ensure_packages(['python-pip'])` is equivalent to `ensure_resource('package', 'python-pip', { ensure => present }`. Therefore, if `python-pip` was previously declared with any other parameters, you'll get a duplicate declaration error.

**Comment by dwerder** [comment]
I asume you are using a python module which does not use ensure_packages to manage your pathon installation. This is more a problem of the other module.

And your problem is on another line: https://github.com/echocat/puppet-graphite/blob/master/manifests/install.pp#L100

```
    ensure_packages(flatten([
      $::graphite::params::python_pip_pkg,
      $::graphite::params::python_dev_pkg,
    ]))
```

**Comment by dwerder** [comment]
One "clean" solution could be, that we do not use trivial package installation in this moduel at all and instead include the "Approved" forge module https://forge.puppetlabs.com/stankevich/python/

That would mean that this python module will become a mandatory dependency.

**Comment by cataphract** [comment]
Well, it's a problem of the other module (where I install a pip package for using postgresql) if your starting point is that the one true way of installing packages is with `ensure_packages` (but even then you have to be careful not to use any parameters other than `ensure => present`). Actually I would prefer that the module gave me the option not to install `python-pip` at all.

**Comment by dwerder** [comment]
Ok, now we can start one of all this discussions how to handle trivial package installation in puppet ;-)

This module was first designed as stand alone. It installs a lot of packages. So we would need a option for gcc, python-pip, ldap, twisted, django, ... etc. If we want to do it right.

To be honest I prefer to use the approved module for python. So I have not to bother with that anymore.

As a workaround you can just clean the variable for $::graphite::params::python_pip_pkg via hiera (so you dont have to change the code of the module) or set it to an empty string in the params file.

**Comment by cataphract** [comment]
But you can't clean `$::graphite::params::python_pip_pkg` via hiera because it's not a parameter of the params class, right? Other parameters seem to be overridable in the init class, but not this one.

**Comment by dwerder** [comment]
You should overwrite it. The yaml file should look like that:

```
---
graphite::params::python_pip_pkg: ''
```

Oh and yes. For puppetlabs ensure_* IS the best practice way to install/create resources, thats because its in the stdlibs module.

**Comment by cintiadr** [comment]
I'm seeing similar problem (I want the packages to be installed via pip, but another module https://github.com/counsyl/puppet-python.git is already installing it, so puppet is telling me it's a dup). 

I was going to suggest an argument like 'do-not-install-pip'.  

Overriding the value via hiera didn't work for me (puppet 3.8.2, hiera 1.3.4, Ubuntu 12.04)

**Comment by dhardy92** [comment]
to me pip installation on the system shouldn't be the responsibility of graphite module. and should be delegated. For example, on debian 7 wheezy, python-pip is totally outdated (1.1) a should be installed via get-pip.py python way.
So I enforce python-pip to be 'absent' on other place conflicting with graphite.

**Comment by amosshapira** [comment]
To me installing software IS part of what I expect from a module - it should usually know best about which package to install for each OS and version and how to install it.

What I increasingly find in some modules are parameters to control what the modules does - install packages, create users, etc. Perhaps the same can be implemented here.
