### ISSUE TITLE
SystemD support

### ISSUE THREAD

**Issue by madAndroid** [echocat/puppet-graphite#211]
Although CentOS7 has a compatibility layer for sysv init scripts, when the carbon daemons start up, and the ordering is such that `/bin/systemctl daemon-reload` has not been run yet, the startup of `carbon-*` issues fails, with a `no such file for directory` message. I've added an exec in our profile modules to deal with this, but this feels as though it's something that should be incorporated within this module.

**Comment by dwerder** [comment]
Yep, systemd support is an issue. The best way would be to add systemd service files to the module to use native systemd. But I have no time for that at the moment.

**Comment by madAndroid** [comment]
> Yep, systemd support is an issue. The best way would be to add systemd service files to the module to use native systemd.

Yes indeed - for the moment we've got a workaround, so it's not crucial... if I find some time, I might look at adding unit files, depending on whether there are any examples floating around the Graphite community.

**Comment by gdhbashton** [comment]
@madAndroid Ha! Just bumped into this exact issue for another cust, fixed it in exactly the same way and THEN found this issue as I was about the file a bug :)

**Comment by madAndroid** [comment]
@gdhbashton - I really wish that the Sys V compatibility layer was handled better by the puppet service provider - IMO, we shouldn't have to be adding random `exec`'s in to handle this - it really feels like the provider should take care of all of this for you. Apparently, the puppet devs don't think so -> https://tickets.puppetlabs.com/browse/PUP-3483
