### ISSUE TITLE
SSL Apache module isn't enabled

### ISSUE THREAD

**Issue by dandunckelman** [echocat/puppet-graphite#223]
When wanting to use SSL with Apache, I think a change needs to be added to run `sudo a2enmod ssl`, otherwise, I get this error:
```
Invalid command ‘SSLEngine’, perhaps misspelled or defined by a module not included
```

If I get around to it, then I'll make a PR.

**Comment by dandunckelman** [comment]
My initial testing was w/ the latest module from the forge.  Getting the latest from here did not result in the aforementioned error.

**Comment by dwerder** [comment]
This is strange, because the latest forge release and the master are identical.
