### ISSUE TITLE
Apache gr_use_ssl fails on CentOS 6

### ISSUE THREAD

**Issue by jnjackins** [echocat/puppet-graphite#250]
On CentOS 6, I get the following error when using `gr_use_ssl = true`:

```
Error: Could not start Service[httpd]: Execution of '/sbin/service httpd start' returned 1: Starting httpd: [Fri Feb 19 05:06:57 2016] [warn] module wsgi_module is already loaded, skipping
Syntax error on line 62 of /etc/httpd/conf.d/graphite.conf:
Invalid command 'SSLEngine', perhaps misspelled or defined by a module not included in the server configuration
[FAILED]
```

It seems that this puppet module should depend on the `mod_ssl` package, at least on redhat-like systems.

**Comment by jnjackins** [comment]
My naïve solution: https://github.com/jnjackins/puppet-graphite/commit/6a9b7d4fdebf767b66b0b12dc507b406ea7a3376

**Comment by dwerder** [comment]
A better way , would be to use the official apache puppet module. How to do it is described here: https://github.com/echocat/puppet-graphite#configure-graphite-with-grafana

That's my recommendation.

**Comment by dwerder** [comment]
Tha fact, that this module is managing things like apache and nginx itself is just historically and will be removed in some future.
