### ISSUE TITLE
RHEL7/Centos7 common package python-crypto

### ISSUE THREAD

**Issue by slivabox** [echocat/puppet-graphite#254]
Looks like carbon-cache is restarted each puppet run.
This happens due to:

> yum install python-crypto
> Loaded plugins: fastestmirror, protectbase
> Loading mirror speeds from cached hostfile
> 0 packages excluded due to repository protections
> Package python-crypto-2.6.1-1.el7.x86_64 is obsoleted by python2-crypto-2.6.1-9.el7.x86_64 which is already installed
> Nothing to do
> 

Example:

> Notice: /Stage[main]/Graphite::Install/Package[python-crypto]/ensure: created
> Info: Class[Graphite::Install]: Scheduling refresh of Class[Graphite::Config]
> Info: Class[Graphite::Install]: Scheduling refresh of Exec[Initial django db creation]
> Info: Class[Graphite::Config]: Scheduling refresh of Exec[Initial django db creation]
> Info: Class[Graphite::Config]: Scheduling refresh of Service[carbon-cache]
> Notice: /Stage[main]/Graphite::Config/Exec[Initial django db creation]: Triggered 'refresh' from 2 events
> Notice: /Stage[main]/Graphite::Config/Service[carbon-cache]: Triggered 'refresh' from 1 events
>

**Comment by dwerder** [comment]
This is fixed in #247 , which is already merged into the `develop` branch.
