### ISSUE TITLE
Invalid relationship: Service[gunicorn] { subscribe => File[/opt/graphite/conf/local_settings.py] }

### ISSUE THREAD

**Issue by huasome** [echocat/puppet-graphite#263]
https://github.com/echocat/puppet-graphite/blob/master/manifests/config_gunicorn.pp#L142
has `subscribe  => File["${graphite::gr_graphiteweb_conf_dir}/local_settings.py"],`

but looking at https://github.com/echocat/puppet-graphite/blob/master/manifests/config.pp#L80, if `gr_pip_install` is set, then local_settings_py_file is at `"${::graphite::gr_graphiteweb_install_lib_dir}/local_settings.py"` instead of `"${::graphite::gr_graphiteweb_conf_dir}/local_settings.py"`.

**Comment by dwerder** [comment]
Take a look at the develop branch. Its already fixed there.
