### ISSUE TITLE
carbon-cache enabled each puppet run

### ISSUE THREAD

**Issue by slivabox** [echocat/puppet-graphite#267]
I am not sure if it's a bug or misconfiguration in my setup.
However, I've got following notice each puppet run:
`Notice: /Stage[main]/Graphite::Config/Service[carbon-cache]/enable: enable changed 'false' to 'true'`

It's happens on:
`CentOS 7.2.1511`
`puppet -V 3.8.6`
`module version 6.0.1`
Could anybody point me out to cause/solution of this?

Kind regards,
Ievgen.

**Comment by dwerder** [comment]
What does `systemctl status carbon-cache` says after a puppet run? Is the service enabled?
Maybe something is disabling it again.

**Comment by slivabox** [comment]
systemctl status carbon-cache:
> ● carbon-cache.service - LSB: Start/Stop carbon-cache
>    Loaded: loaded (/etc/rc.d/init.d/carbon-cache)
>    Active: active (running) since Fri 2016-04-08 11:02:42 UTC; 2 days ago
>      Docs: man:systemd-sysv-generator(8)
>    CGroup: /system.slice/carbon-cache.service
>            └─27260 python -W ignore /opt/graphite/bin/carbon-cache.py --instance=a start
> 
> Apr 08 11:02:41 host-10-66-11-241.net-10-66-0-0.tt3.com systemd[1]: Starting LSB: Start/Stop carbon-cache...
> Apr 08 11:02:42 host-10-66-11-241.net-10-66-0-0.tt3.com carbon-cache[27249]: Starting carbon-cache:a...[  OK  ]
> Apr 08 11:02:42 host-10-66-11-241.net-10-66-0-0.tt3.com systemd[1]: Started LSB: Start/Stop carbon-cache.

systemctl is-enabled carbon-cache:
> carbon-cache.service is not a native service, redirecting to /sbin/chkconfig.
> Executing /sbin/chkconfig carbon-cache --level=5
> enabled
>

chkconfig --list |grep carbon-cache:
> 
> Note: This output shows SysV services only and does not include native
>       systemd services. SysV configuration data might be overridden by native
>       systemd configuration.
> 
>       If you want to list systemd services use 'systemctl list-unit-files'.
>       To see services enabled on particular target use
>       'systemctl list-dependencies [target]'.
> 
> carbon-cache   	0:off	1:off	2:on	3:on	4:on	5:on	6:off

**Comment by squarebracket** [comment]
This is because of the explicit provider being `redhat` instead of `systemd`, so it uses the old-style initscript which doesn't have support for `systemctl enable`. This is fixed in #281 by making `service_provider` be `systemd` for RHEL7 and friends.
