### ISSUE TITLE
manual steps needed on first apply

### ISSUE THREAD

**Issue by captnswing** [echocat/puppet-graphite#279]
when applying the vanilla `class { 'graphite': }` on my Ubuntu Trusty host for the first time, some directories are missing. I had to

```shell
sudo mkdir -p /var/log/httpd/graphite-web/
sudo chown -R www-data /var/log/httpd/
sudo mkdir -p /var/lib/graphite-web/
sudo chown -R www-data /var/lib/graphite-web/
```
also, the wsgi file referenced in `/etc/apache2/sites-enabled/graphite.conf`is wrong. I had to 

```shell
sudo mv /opt/graphite/conf/graphite_wsgi.py /opt/graphite/conf/graphite.wsgi
sudo service apache2 restart
```

to get things going

**Comment by dwerder** [comment]
We have two solution for that on the hand:

1. Set the correct apache log dir for teh different distro in teh params.pp
  - RedHat: /var/log/httpd/
  - Debian: /var/log/apache2/

2. Store the logs at the graphite storage: `$gr_graphitewb_log_dir` (default would be /opt/graphite/storage/log/ )

I would prefer the second one.

**Comment by dwerder** [comment]
The `gr_graphite_web_storage_dir` = /var/lib/graphite-wb/  should be set to the default `$gr_storage_dir/graphite-web`

**Comment by dwerder** [comment]
This two issues should be fixed in the develop branch.
