### ISSUE TITLE
Cannot find comand pip

### ISSUE THREAD

**Issue by superjeb** [echocat/puppet-graphite#287]
When I run this on RHEL 6.5  it cannot find pip. 

python-pip is installed   and path is correct.   

Any idea?

**Comment by BigAl** [comment]
Add this:

  file { '/usr/bin/pip-python':
    ensure  => 'link',
    target  => '/usr/bin/pip',
    require => Package["python-pip"]
  }

to you own code to workaround this issue is due to changing name of python-pip to pip in the packages there are a few issues raised with puupetlabs about this
