### ISSUE TITLE
gr_use_ssl not used by Nginx

### ISSUE THREAD

**Issue by rickatnight11** [echocat/puppet-graphite#291]
The `gr_use_ssl` parameter is only used by Apache:

```
[root@mgmt01 graphite]# grep -R use_ssl .
./templates/etc/apache2/sites-available/graphite.conf.erb:<% if scope.lookupvar('graphite::gr_use_ssl') %>
./README.md:#####`gr_use_ssl`
./manifests/init.pp:# [*gr_use_ssl*]
./manifests/init.pp:  $gr_use_ssl                             = false,
./manifests/init.pp:  validate_bool($gr_use_ssl)
```

**Comment by dwerder** [comment]
Thats correct. I will fix the README.

**Comment by rickatnight11** [comment]
By closing this, are you not planning to fix it, or are you tracking this feature elsewhere?

**Comment by dwerder** [comment]
I documented, that it doesn't work with nginx. At the moment I have no time to update the nginx template to use it. But it wouldnt be that hard. So if you want that feature and have time send a pull request against the develop branch.

**Comment by rickatnight11** [comment]
Cool, I was planning on looking into it, but wanted to confirm that you weren't tracking or working on it elsewhere.
