### ISSUE TITLE
Issues when using example snippet (Configure Graphite with Grafana) on CentOS7

### ISSUE THREAD

**Issue by 030** [echocat/puppet-graphite#293]
1

```
Error: Evaluation Error: Unknown function: 'my'. at ../manifests/site.pp:37:25 on node localhost
```

2

```
Error: Evaluation Error: Error while evaluating a Function Call, Having $gr_web_server => 'none' requires use of $gr_web_user and $gr_web_group to set correct file owner for your own webserver setup. at ../modules/graphite/manifests/config.pp:67:9 on node localhost
```

**Comment by 030** [comment]
Thank you for fixing. Could you explain why `Error: Evaluation Error: Error while evaluating a Function Call, Having $gr_web_server => 'none' requires use of $gr_web_user and $gr_web_group to set correct file owner for your own webserver setup. at ../modules/graphite/manifests/config.pp:67:9 on node localhost` occurs?

**Comment by dwerder** [comment]
<I think teh message is straight forward. You have to set the two parameteres. Because the graphite module has to set the correct file owner ships and doesn't know what user your webserver will requiere. I asume you are using Apache. So it will be www-data or apache, depending on the distribution you are using.

**Comment by 030** [comment]
Yes. I was assuming that that would have been included in the example snippet

**Comment by dwerder** [comment]
How should the example know., what distribution or webserver you are using?

**Comment by 030** [comment]
Regarding the ```webserver``` it is apache as it is defined in the snippet

**Comment by 030** [comment]
The apache user on centos7 seems to be apache as well
