### ISSUE TITLE
graphite.erb wrong

### ISSUE THREAD

**Issue by gennady-voronkov** [echocat/puppet-graphite#324]
proxy_pass http://<%= scope.lookupvar('graphite::gunicorn_bind') %>:/;
instead of this, should be next line:
proxy_pass http://<%= scope.lookupvar('graphite::gunicorn_bind') %>;

**Comment by dwerder** [comment]
fixed in https://github.com/echocat/puppet-graphite/commit/914537594a5474cd9d9b7f86a7cb86af052909da

**Comment by gennady-voronkov** [comment]
great, thanks a lot
