### ISSUE TITLE
Error : can't change default directory because of pip

### ISSUE THREAD

**Issue by tpoindessous** [echocat/puppet-graphite#339]
Hi

I try to change default directory for graphite via `gr_base_dir` parameter.

But pip installs packages in `/opt/graphite`. So I would like to use the new parameter :
```
gr_pip_install_options    =>
      [ '--install-option="--prefix=/tmp/graphite/graphite"',
        '--install-option="--install-lib=/tmp/graphite/graphite/lib"',
      ],
```

but it won't work since only few packages (carbon, graphite-web) need this option.

Could you, please, provide a method to install (without pip ?) in a different directory than /opt/graphite/ ?

Thanks.

**Comment by dwerder** [comment]
Years old and closed.
