### ISSUE TITLE
[Enhancement] make the installation of graphite-web optional 

### ISSUE THREAD

**Issue by tpoindessous** [echocat/puppet-graphite#340]
Hi

we use your module and we would like to thank you for your work.

We use grafana, so we don't need graphite-web. Could you, please, make this "add-on" optional ? 
It would make our installation simplier , no need for mysql for example.

Thanks in advance !

Thomas.

**Comment by dwerder** [comment]
If you want that implemented, then you can create a PR. I have no time for that right now and I think it would be a bigger change. Tests have to be written and so on.
