### ISSUE TITLE
Can you release a new version in the forge, please ?

### ISSUE THREAD

**Issue by tpoindessous** [echocat/puppet-graphite#342]
Hi

few days ago, you have merged a PR in your develop branch.

If you are OK with that, could you, please, release a new version in the forge ?

I use your puppet module but I was forced to clone it in my own repo to be able to use it with the patch. I would really appreciate to switch back to an official module in the puppetforge.

Thanks for your time and your work.

**Comment by tpoindessous** [comment]
Hi

I saw this summer that you have begin to prepare release for 7.2.0

Could you, please, finish this release and publish it on puppet forge ?

Thanks !!!

**Comment by dwerder** [comment]
Done!

**Comment by tpoindessous** [comment]
Thanks !
