### ISSUE TITLE
ensuring order for storage aggregation rules

### ISSUE THREAD

**Issue by david-jana** [echocat/puppet-graphite#365]
It looks like a hash map is used to configure the storage aggregation rules and sorted before creating the storage-aggregation.conf.  This means the alphabetical order of the aggregation rule names needs to match the order in which the rules should appear in the .conf file in order for the 'first matching rule is used' principle to work correctly.

By contrast, the storage schema rules are configured using a list which means that the order in which the storage schema rules are written in the puppet .pp file will be preserved in the storage-schemas.conf file that is created.  

Using a list to configure the rules seems more intuitive and less likely to result in unintentional reordering of the rules.  Is it possible to change the way the storage-aggregation rules are configured to use a list instead of a hash map?

**Comment by costimuraru** [comment]
👍 
this bit us hard, because 

```json
  'max':
    pattern: '\.max$'
    factor: '0'
    method: 'max'
  'sum':
    pattern: '\.count$'
    factor: '0'
    method: 'sum'
  'default':
    pattern: '.*'
    factor: '0'
    method: 'average'
```

got translated into
```json
  'default':
    pattern: '.*'
    factor: '0'
    method: 'average'
  'max':
    pattern: '\.max$'
    factor: '0'
    method: 'max'
  'sum':
    pattern: '\.count$'
    factor: '0'
    method: 'sum'
```

This means all the metrics used average as aggregation type (even the counts/max/min etc.).

**Comment by dwerder** [comment]
Thnaks for sharing that information. You are free to send a PR.

**Comment by dwerder** [comment]
Changed just a few years later ;-)
