### ISSUE TITLE
Support Debian Buster

### ISSUE THREAD

**Issue by runemy** [echocat/puppet-graphite#385]
I'm trying to install this on Debian Buster without success. Please add support for Debian Buster.

**Comment by jakethedev** [comment]
I'd like to make some noise here too, I'm working at a software shop that is trying to finish moving some infra to puppet and 18.04 and we rely a lot on graphite, so this support would seriously improve our lives 😄

**Comment by dwerder** [comment]
Hello guys,
to be honest I do not work with puppet anymore. (switched company and its ansible now) So I do not really maintain that module anymore. If you send pull requests against the develop branch I will see to merge them.

Or someone will fork that repo.
