### ISSUE TITLE
manage.py no more available from graphite-web 1.0.x

### ISSUE THREAD

**Issue by meni2029** [echocat/puppet-graphite#398]
Hello,

I have tried to upgrade puppet-graphite from 7.3.0 to commit: https://github.com/echocat/puppet-graphite/commit/64027542ddab9962640bcb2d52c8146048312523
It failed at `Exec[Initial django db creation]`

There are references to file **manage.py** in `manifests/config.pp` and `manifests/init.pp` , but **manage.py** is not anymore in graphite-web from version 1.0.x

Here are 2 issues related to this: https://github.com/graphite-project/graphite-web/issues/568 and https://github.com/graphite-project/graphite-web/issues/1984

I am not sure if I'm doing something wrong.
System: CentOS Linux release 7.8.2003
Puppet: agent 4.10.12 master 4.6.1
Python: 2.7
gr_pip_install: true

Cheers

**Comment by dwerder** [comment]
There is a solution to this. See the section "Install Graphite 1.1 and enable tag-support" in the README.md.
I will adjust the default for v8.0.1 to match the graphite 1.1 requirements.

**Comment by meni2029** [comment]
Hello Daniel, thanks for pointing to the solution 👍 
I have it working now by setting `gr_django_init_command` and `gr_django_init_provider` (in my case django-admin.py is located under /usr/bin/).
