### ISSUE TITLE
use upstream web server modules like puppetlabs/apache

### ISSUE THREAD

**Issue by neoice** [echocat/puppet-graphite#78]
many modules are now depending on upstream httpd configuration modules instead of reinventing the wheel. this makes it easier to use multiple modules together and avoid duplicate package declarations. it would be nice to have here :)

I'm not sure what the "preferred" solution for ngnix is, but puppetlabs/apache seems to be dominating the ecosystem for apache management.

**Comment by dwerder** [comment]
This brings me to the point, that I will just drop all that built-in Apache support and instead give an README example how to configure things with separate modules.

Like
```
class { apache: }
apache::vhost {foo bar}
class {graphite: }

Class[apache]->Class[graphite]
```

**Comment by brettswift** [comment]
@dwerder  your last comment would work in my use case.   The difficulty I'm finding is getting up and running with graphite and grafana on the same server.  Both graphite and grafana have puppet modules but they don't work well together without a lot of intervention. 

For this use case,  this module could configure an `apache::vhost`, and then external modules (grafana) could also use the `apache::vhost` module.   The puppet catalog would compile them at the same time as long as the vhosts were unique (great candidate for a parameter to inject) and then this module and external modules on the same server would be compatible.

I think that'd be a powerful way of utilizing the apache module.

Just a thought!

**Comment by iverberk** [comment]
I agree with @brettswift , it would be really nice to install graphite and grafana (with your modules) on the same server without running into duplicate declaration issues. Current workaround is to disable apache config and just create the vhost manually elsewhere for grafana and graphite?

**Comment by dwerder** [comment]
It works right now. You can take a look here:  https://github.com/echocat/puppet-grafana/issues/8

**Comment by dwerder** [comment]
As mention in the ticket above, the next major version 6 will use the puppetlabs/apache module if you `use gr_web_server => 'apache'` and the default will become 'none'. So that you can provide your own webserver config.

**Comment by brettswift** [comment]
Thanks @dwerder - that's what I was looking for.   Github search-fu  was not good apparently. 

It might be helpful to get that example vhost configuration into the README file.

Will the next major release let you inject a vhost name, and port, and encapsulate all the graphite specifics under the hood from the example in echocat/puppet-grafana#8 ?

**Comment by dwerder** [comment]
Thats the plan

**Comment by dwerder** [comment]
Should be done, but will not happen at the moment.
